### PR TITLE
minimatch@^3.0.2

### PR DESCRIPTION
**Pull request by KenanY**
Contains a fix for a RegExp DoS issue. Only breaking change between 2 and 3 was the removal of the browserified version from the published package.

Tests pass locally for me.

### CODE REVIEW

**Comment by abritinthebay** [comment]
Can we get an update on this PR? This is an important fix.

**Comment by yoshuawuyts** [comment]
Sure, I'll give this a closer look

**Comment by yoshuawuyts** [comment]
LGTM

**Comment by yoshuawuyts** [comment]
published as `v3.0.3` :tada:

**Pull request merged**
